### ISSUE TITLE
Consider making inlined functions translation unit independent

### ISSUE THREAD

**Issue by Player01osu** [ccgargantua/arena-allocator#14]
Currently, certain functions are annotated with `extern inline`. In my opinion, this doesn't really make sense, as inlining a function "inserts" the respective code directly into the call site, so it wouldn't make sense to emit their symbol in the object files.

## Option 1 - Move inline functions outside of 'implementation' `ifdef` and `static inline` them

I believe this approach would be the most appropriate for the inlined functions. On top of being more technically correct as to what the compiler is doing, it also serves to document what is actually happening when using the functions (ie: the functions are being "copied" at every call site).

## Option 2 - Do not `inline` functions

Inlining these functions will not benefit performance for a vast majority of use cases. It should, therefore, be removed and users who may benefit from aggressive inlining can add the respective annotations themselves.

**Comment by ccgargantua** [comment]
I like option 2. Want to do it? @Player01osu
